### ISSUE TITLE
Invalid Logging Configuration: The CloudWatch Logs Resource Policy size was exceeded. 

### ISSUE THREAD

**Issue by gmarchand** [aws-samples/media-analysis-policy-evaluation-framework#4]
Error:
'''
Resource handler returned message: "Invalid Logging Configuration: The CloudWatch Logs Resource Policy size was exceeded. We suggest prefixing your CloudWatch log group name with /aws/vendedlogs/states/. 
'''

![image](https://github.com/aws-samples/media-analysis-policy-evaluation-framework/assets/308444/96e0ba6d-cb57-4b99-83e3-390c7c23b9ca)
![image](https://github.com/aws-samples/media-analysis-policy-evaluation-framework/assets/308444/52050bf2-c710-4ab6-9450-af303e394c40)

**Comment by lanazhang** [comment]
This issue is due to a region limit on CloudWatch Resource Policies. The new build includes the /aws/vendedlogs/states/ prefix for the StepFunctions log group in the CDK package to avoid this issue.

**Comment by lanazhang** [comment]
Please re-open if you still see it happen.

**Comment by lanazhang** [comment]
Please re-open if you still see it happen.

**Comment by lanazhang** [comment]
Please re-open if you still see it happen.
